# Generated by Django 4.2.6 on 2023-10-28 12:15

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='updated_at'),
        ),
    ]
