# Generated by Django 4.2.6 on 2023-10-30 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 16, 56, 28, 85196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 16, 56, 28, 86836, tzinfo=datetime.timezone.utc), verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='precde',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='accounts.mobileprecode'),
        ),
    ]
