# Generated by Django 4.2.6 on 2023-10-28 14:14

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 14, 25, 896563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 14, 25, 897317, tzinfo=datetime.timezone.utc), verbose_name='last login'),
        ),
    ]
