# Generated by Django 4.2.6 on 2023-10-30 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_created_at_alter_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 16, 57, 15, 825051, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 16, 57, 15, 826605, tzinfo=datetime.timezone.utc), verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='precde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='accounts.mobileprecode'),
        ),
    ]
