# Generated by Django 4.2.6 on 2023-10-28 15:05

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_created_at_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 15, 5, 14, 32174, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 15, 5, 14, 32781, tzinfo=datetime.timezone.utc), verbose_name='last login'),
        ),
    ]
