# Generated by Django 4.2.6 on 2023-10-28 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('explain_to_me', models.TextField(verbose_name='explain to me')),
            ],
            options={
                'verbose_name': 'about_me',
                'verbose_name_plural': 'abouts_me',
                'db_table': 'about_mee',
            },
        ),
        migrations.CreateModel(
            name='AboutMeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('image', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=50, verbose_name='full_name')),
                ('explain', models.TextField(max_length=255, verbose_name='explain')),
            ],
            options={
                'verbose_name': 'about_me',
                'verbose_name_plural': 'abouts_me',
                'db_table': 'about_me',
            },
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='email')),
                ('mobile_phone', models.CharField(blank=True, max_length=11, unique=True, verbose_name='mobile_phone')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'content us',
                'verbose_name_plural': 'contents_us',
                'db_table': 'contents',
            },
        ),
        migrations.CreateModel(
            name='ContentInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='full_name')),
                ('mobile_phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='mobile_phone')),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='email')),
                ('explane_me', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'contact_info',
                'verbose_name_plural': 'contacts_info',
                'db_table': 'contact_info',
            },
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('title_education', models.CharField(max_length=100, verbose_name='education')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
            ],
            options={
                'verbose_name': 'education',
                'verbose_name_plural': 'educations',
                'db_table': 'educations',
            },
        ),
        migrations.CreateModel(
            name='ExpreiencModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('exprense_title', models.CharField(max_length=50, verbose_name='exprience')),
                ('explain_exprence', models.CharField(max_length=255, verbose_name='explain')),
                ('at_date_exprence', models.DateField(default=django.utils.timezone.now, verbose_name='at date')),
                ('to_date_exprence', models.DateField(default=django.utils.timezone.now, verbose_name='to date')),
            ],
            options={
                'verbose_name': 'exprence',
                'verbose_name_plural': 'exprences',
                'db_table': 'exprences',
            },
        ),
        migrations.CreateModel(
            name='HeaderConetent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('text', models.CharField(max_length=50, verbose_name='text')),
            ],
            options={
                'verbose_name': 'header_conetent',
                'verbose_name_plural': 'header_conetents',
                'db_table': 'header_conetent',
            },
        ),
        migrations.CreateModel(
            name='HeaderConetentSciol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('sciol_name', models.CharField(max_length=20, verbose_name='sciol name')),
                ('sciol_url', models.URLField(verbose_name='sciol url')),
            ],
            options={
                'verbose_name': 'header_conetent sciol',
                'verbose_name_plural': 'header conetents sciol',
                'db_table': 'sciol',
            },
        ),
        migrations.CreateModel(
            name='NvbarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('navbar_name', models.CharField(max_length=20, verbose_name='Name')),
                ('navbar_status', models.CharField(choices=[('pb', 'Publish'), ('rj', 'Reject')], default='pb', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'navbar',
                'verbose_name_plural': 'navbars',
                'db_table': 'navbar',
                'ordering': ('-navbar_name',),
            },
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated_at')),
                ('skill_name', models.CharField(max_length=50, verbose_name='skill_name')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='image')),
            ],
            options={
                'verbose_name': 'skill_mode',
                'verbose_name_plural': 'skill_modes',
                'db_table': 'skill',
            },
        ),
    ]
