# Generated by Django 4.2.6 on 2023-10-28 14:09

import datetime
from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 9, 23, 652954, tzinfo=datetime.timezone.utc))),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('full_name', models.CharField(max_length=50, verbose_name='full_name')),
                ('explain', models.TextField(max_length=255, verbose_name='explain')),
            ],
            options={
                'verbose_name': 'about me',
                'verbose_name_plural': 'abouts me',
                'db_table': 'about_me',
            },
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 9, 23, 652954, tzinfo=datetime.timezone.utc))),
                ('full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='email')),
                ('mobile_phone', models.CharField(blank=True, max_length=11, unique=True, verbose_name='mobile_phone')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'content us',
                'verbose_name_plural': 'contents_us',
                'db_table': 'contents',
            },
        ),
        migrations.CreateModel(
            name='ContentInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='full_name')),
                ('mobile_phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='mobile_phone')),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='email')),
                ('explane_me', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'contact_info',
                'verbose_name_plural': 'contacts_info',
                'db_table': 'contact_info',
            },
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 9, 23, 652954, tzinfo=datetime.timezone.utc))),
                ('title_education', models.CharField(max_length=100, verbose_name='education name')),
                ('text', models.TextField(max_length=255, verbose_name='sayTell me a little bit about it. ')),
                ('at_education', django_jalali.db.models.jDateTimeField(verbose_name='at time')),
                ('to_education', django_jalali.db.models.jDateTimeField(verbose_name='to time')),
            ],
            options={
                'verbose_name': 'education',
                'verbose_name_plural': 'educations',
                'db_table': 'educations',
            },
        ),
        migrations.CreateModel(
            name='ExpreiencModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 9, 23, 652954, tzinfo=datetime.timezone.utc))),
                ('exprense_title', models.CharField(max_length=50, verbose_name='exprience')),
                ('explain_exprence', models.CharField(max_length=255, verbose_name='explain')),
                ('at_date_exprence', models.DateField(default=django.utils.timezone.now, verbose_name='at date')),
                ('to_date_exprence', models.DateField(default=django.utils.timezone.now, verbose_name='to date')),
            ],
            options={
                'verbose_name': 'exprence',
                'verbose_name_plural': 'exprences',
                'db_table': 'exprences',
            },
        ),
        migrations.CreateModel(
            name='HeaderConetent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 9, 23, 652954, tzinfo=datetime.timezone.utc))),
                ('text', models.CharField(max_length=50, verbose_name='text')),
            ],
            options={
                'verbose_name': 'header conetent',
                'verbose_name_plural': 'header conetents',
                'db_table': 'header_conetent',
            },
        ),
        migrations.CreateModel(
            name='HeaderConetentSciol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 9, 23, 652954, tzinfo=datetime.timezone.utc))),
                ('sciol_name', models.CharField(max_length=20, verbose_name='sciol name')),
                ('sciol_url', models.URLField(verbose_name='sciol url')),
            ],
            options={
                'verbose_name': 'header_conetent sciol',
                'verbose_name_plural': 'header conetents sciol',
                'db_table': 'sciol',
            },
        ),
        migrations.CreateModel(
            name='NvbarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 9, 23, 652954, tzinfo=datetime.timezone.utc))),
                ('navbar_name', models.CharField(max_length=20, verbose_name='Name')),
                ('navbar_status', models.CharField(choices=[('pb', 'Publish'), ('rj', 'Reject')], default='pb', max_length=2, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'navbar',
                'verbose_name_plural': 'navbars',
                'db_table': 'navbar',
            },
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 9, 23, 652954, tzinfo=datetime.timezone.utc))),
                ('skill_name', models.CharField(max_length=50, verbose_name='skill_name')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='image')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'db_table': 'skill',
            },
        ),
    ]
