# Generated by Django 4.2.6 on 2023-11-01 08:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 2, 6, 361711, tzinfo=datetime.timezone.utc))),
                ('full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('mobile_phone', models.CharField(blank=True, max_length=11, verbose_name='mobile_phone')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'content us',
                'verbose_name_plural': 'contents us',
                'db_table': 'contents',
            },
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 2, 6, 361711, tzinfo=datetime.timezone.utc))),
                ('skill_name', models.CharField(max_length=50, verbose_name='skill_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='SciolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 2, 6, 361711, tzinfo=datetime.timezone.utc))),
                ('sciol_name', models.CharField(max_length=20, verbose_name='sciol name')),
                ('sciol_url', models.CharField(max_length=255, verbose_name='sciol url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sciol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sciol',
                'verbose_name_plural': 'sciols',
                'db_table': 'sciol',
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 2, 6, 361711, tzinfo=datetime.timezone.utc))),
                ('title', models.CharField(max_length=50, verbose_name='title project')),
                ('project_url', models.URLField(verbose_name='project url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('status_project', models.CharField(choices=[('s', 'start'), ('d', 'doing'), ('c', 'complate')], default='c', max_length=1, verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ExpreienceWorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 2, 6, 361711, tzinfo=datetime.timezone.utc))),
                ('exprience_title', models.CharField(max_length=50, verbose_name='experience title')),
                ('explain_exprence', models.TextField(help_text='Tell me something about your work experience.', max_length=500, verbose_name='explain to own experience')),
                ('link_company', models.URLField(blank=True, null=True, verbose_name='link to company')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('at_date_exprence', django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='at date')),
                ('to_date_exprence', django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='to date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'exprence',
                'verbose_name_plural': 'exprences',
                'db_table': 'exprences',
            },
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 2, 6, 361711, tzinfo=datetime.timezone.utc))),
                ('title_education', models.CharField(max_length=100, verbose_name='education name')),
                ('explain_education', models.TextField(help_text='Describe where you were trained and educated', max_length=500, verbose_name='explain education')),
                ('at_education', django_jalali.db.models.jDateField(verbose_name='at time')),
                ('to_education', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='to time')),
                ('status_education', models.BooleanField(default=False, verbose_name='status education')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'education',
                'verbose_name_plural': 'educations',
                'db_table': 'educations',
            },
        ),
        migrations.CreateModel(
            name='AboutMeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 2, 6, 361711, tzinfo=datetime.timezone.utc))),
                ('image', models.ImageField(blank=True, help_text='Post a picture of yourself', upload_to='')),
                ('explain', models.TextField(help_text='Write something about yourself', max_length=500, verbose_name='explain')),
                ('job', models.CharField(blank=True, help_text='What is your current job?', max_length=50, null=True, verbose_name='job')),
                ('marital_status', models.CharField(choices=[('s', 'single'), ('m', 'married')], default='s', max_length=1, verbose_name='marital status')),
                ('gender_choose', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1, verbose_name='gender')),
                ('address', models.TextField()),
                ('birth_day', django_jalali.db.models.jDateField(default=datetime.date(2023, 11, 1), verbose_name='birth day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='about', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'about me',
                'verbose_name_plural': 'abouts me',
                'db_table': 'about_me',
            },
        ),
    ]
