# Generated by Django 4.2.6 on 2023-11-01 08:21

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationmodel',
            name='title_education',
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='fields_of_study',
            field=models.CharField(default=0, max_length=100, verbose_name='field of study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='university',
            field=models.CharField(default=1, max_length=100, verbose_name='university'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 20, 59, 418080, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 20, 59, 418080, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 20, 59, 418080, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 20, 59, 418080, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 20, 59, 418080, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sciolmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 20, 59, 418080, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 8, 20, 59, 418080, tzinfo=datetime.timezone.utc)),
        ),
    ]
