# Generated by Django 4.2.6 on 2023-11-01 10:45

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodels',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='birth_day',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.date(2023, 11, 1), verbose_name='birth day'),
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 45, 28, 701112, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='explain',
            field=models.TextField(blank=True, help_text='Write something about yourself', max_length=500, verbose_name='explain'),
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='gender_choose',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('s', 'single'), ('m', 'married')], default='s', max_length=1, verbose_name='marital status'),
        ),
        migrations.AlterField(
            model_name='awardsmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 45, 28, 701112, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='boookarticlemodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 45, 28, 701112, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 45, 28, 701112, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='at_education',
            field=django_jalali.db.models.jDateField(blank=True, verbose_name='at time'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 45, 28, 701112, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='explain_education',
            field=models.TextField(blank=True, help_text='Describe where you were trained and educated', max_length=500, verbose_name='explain education'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='fields_of_study',
            field=models.CharField(blank=True, max_length=100, verbose_name='field of study'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='status_education',
            field=models.BooleanField(blank=True, default=False, verbose_name='studying'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='university',
            field=models.CharField(blank=True, max_length=100, verbose_name='university'),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 45, 28, 701112, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 45, 28, 701112, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sciolmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 45, 28, 701112, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 45, 28, 701112, tzinfo=datetime.timezone.utc)),
        ),
    ]
