# Generated by Django 4.2.6 on 2023-10-28 12:15

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='aboutmemodel',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='expreiencmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='expreiencmodel',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='headerconetent',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='headerconetent',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='headerconetentsciol',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='headerconetentsciol',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='nvbarmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='nvbarmodel',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='updated_at'),
        ),
    ]
