# Generated by Django 4.2.6 on 2023-10-28 14:14

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusmodel',
            options={'verbose_name': 'content us', 'verbose_name_plural': 'contents us'},
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 14, 25, 896563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 14, 25, 896563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 14, 25, 896563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreiencmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 14, 25, 896563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetent',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 14, 25, 896563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetentsciol',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 14, 25, 896563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nvbarmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 14, 25, 896563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 14, 25, 896563, tzinfo=datetime.timezone.utc)),
        ),
    ]
