# Generated by Django 4.2.6 on 2023-10-30 16:56

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 16, 56, 28, 85196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 16, 56, 28, 85196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 16, 56, 28, 85196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 16, 56, 28, 85196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 16, 56, 28, 85196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sciolmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 16, 56, 28, 85196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 16, 56, 28, 85196, tzinfo=datetime.timezone.utc)),
        ),
    ]
