# Generated by Django 4.2.6 on 2023-11-01 10:47

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_aboutmemodels_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 47, 11, 469020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='awardsmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 47, 11, 469020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='boookarticlemodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 47, 11, 469020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 47, 11, 469020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 47, 11, 469020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 47, 11, 469020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 47, 11, 469020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sciolmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 47, 11, 469020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 47, 11, 469020, tzinfo=datetime.timezone.utc)),
        ),
    ]
