# Generated by Django 4.2.6 on 2023-10-28 14:22

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contactusmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerconetent',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 22, 12, 213038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 22, 12, 213038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 22, 12, 213038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreiencmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 22, 12, 213038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetent',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 22, 12, 213038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetentsciol',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 22, 12, 213038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nvbarmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 22, 12, 213038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 22, 12, 213038, tzinfo=datetime.timezone.utc)),
        ),
    ]
