# Generated by Django 4.2.6 on 2023-11-01 10:56

import datetime
from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_aboutmemodels_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 56, 39, 833723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='awardsmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 56, 39, 833723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='boookarticlemodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 56, 39, 833723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 56, 39, 833723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 56, 39, 833723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='at_date_exprence',
            field=django_jalali.db.models.jDateField(blank=True, default=django.utils.timezone.now, verbose_name='at date'),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 56, 39, 833723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='explain_your_duties',
            field=models.TextField(blank=True, help_text='Tell me something about your work experience.', max_length=500, verbose_name='explain your duties'),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='job title'),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='organization_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='status_work',
            field=models.CharField(choices=[('b', 'I am busy now'), ('d', 'I dont work here anymore')], default='d', max_length=1, verbose_name='status work'),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='to_date_exprence',
            field=django_jalali.db.models.jDateField(blank=True, default=django.utils.timezone.now, verbose_name='to date'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 56, 39, 833723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sciolmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 56, 39, 833723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 10, 56, 39, 833723, tzinfo=datetime.timezone.utc)),
        ),
    ]
