# Generated by Django 4.2.6 on 2023-11-01 11:05

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_aboutmemodels_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodels',
            name='birth_day',
            field=django_jalali.db.models.jDateField(blank=True, verbose_name='birth day'),
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 5, 15, 746325, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='awardsmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 5, 15, 746325, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='awardsmodel',
            name='year_awards',
            field=django_jalali.db.models.jDateField(verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='boookarticlemodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 5, 15, 746325, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='boookarticlemodel',
            name='year',
            field=django_jalali.db.models.jDateField(blank=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 5, 15, 746325, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 5, 15, 746325, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='at_date_exprence',
            field=django_jalali.db.models.jDateField(blank=True, verbose_name='at date'),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 5, 15, 746325, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='status_work',
            field=models.CharField(choices=[('b', 'I am busy now'), ('d', 'I dont work here'), ('f', 'looking for work')], default='d', max_length=1, verbose_name='status work'),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='to_date_exprence',
            field=django_jalali.db.models.jDateField(blank=True, verbose_name='to date'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 5, 15, 746325, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='from_date',
            field=django_jalali.db.models.jDateField(verbose_name='from date'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='up_to_date',
            field=django_jalali.db.models.jDateField(verbose_name='up to date'),
        ),
        migrations.AlterField(
            model_name='sciolmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 5, 15, 746325, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 5, 15, 746325, tzinfo=datetime.timezone.utc)),
        ),
    ]
