# Generated by Django 4.2.6 on 2023-10-28 14:48

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutmemodels_email_aboutmemodels_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 48, 18, 242409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 48, 18, 242409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='at_education',
            field=django_jalali.db.models.jDateField(verbose_name='at time'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 48, 18, 242409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='text',
            field=models.TextField(max_length=255, verbose_name='sayTell me a little bit about it education. '),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='to_education',
            field=django_jalali.db.models.jDateField(verbose_name='to time'),
        ),
        migrations.AlterField(
            model_name='expreiencmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 48, 18, 242409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetent',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 48, 18, 242409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetentsciol',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 48, 18, 242409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nvbarmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 48, 18, 242409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 14, 48, 18, 242409, tzinfo=datetime.timezone.utc)),
        ),
    ]
