# Generated by Django 4.2.6 on 2023-11-01 11:34

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_aboutmemodels_birth_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 34, 46, 867999, tzinfo=datetime.timezone.utc))),
                ('auther', models.CharField(blank=True, max_length=100, verbose_name='auther')),
            ],
            options={
                'verbose_name': 'authore',
                'verbose_name_plural': 'authore',
                'db_table': 'authore',
            },
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 34, 46, 867999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='awardsmodel',
            name='awards_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='awards_name'),
        ),
        migrations.AlterField(
            model_name='awardsmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 34, 46, 867999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='awardsmodel',
            name='explain_awards',
            field=models.TextField(blank=True, max_length=500, verbose_name='explain awards'),
        ),
        migrations.AlterField(
            model_name='awardsmodel',
            name='year_awards',
            field=django_jalali.db.models.jDateField(blank=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='boookarticlemodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 34, 46, 867999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 34, 46, 867999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 34, 46, 867999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 34, 46, 867999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 34, 46, 867999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='from_date',
            field=django_jalali.db.models.jDateField(blank=True, verbose_name='from date'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_url',
            field=models.URLField(blank=True, verbose_name='project url'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='title project'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='up_to_date',
            field=django_jalali.db.models.jDateField(blank=True, verbose_name='up to date'),
        ),
        migrations.AlterField(
            model_name='sciolmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 34, 46, 867999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sciolmodel',
            name='sciol_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='sciol name'),
        ),
        migrations.AlterField(
            model_name='sciolmodel',
            name='sciol_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='sciol url'),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 34, 46, 867999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='skill_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='skill_name'),
        ),
    ]
