# Generated by Django 4.2.6 on 2023-11-01 11:35

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_authoremodel_alter_aboutmemodels_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 35, 34, 351344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='authoremodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 35, 34, 351344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='awardsmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 35, 34, 351344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='boookarticlemodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 35, 34, 351344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='boookarticlemodel',
            name='publisher',
            field=models.ManyToManyField(related_name='authors', to='home.authoremodel'),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 35, 34, 351344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 35, 34, 351344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreienceworkmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 35, 34, 351344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 35, 34, 351344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sciolmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 35, 34, 351344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 11, 1, 11, 35, 34, 351344, tzinfo=datetime.timezone.utc)),
        ),
    ]
