# Generated by Django 4.2.6 on 2023-10-28 15:01

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_aboutmemodels_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expreiencmodel',
            name='link_project',
            field=models.URLField(default=0, verbose_name='link to project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 15, 0, 37, 499222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 15, 0, 37, 499222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 15, 0, 37, 499222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreiencmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 15, 0, 37, 499222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetent',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 15, 0, 37, 499222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetentsciol',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 15, 0, 37, 499222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nvbarmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 15, 0, 37, 499222, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 28, 15, 0, 37, 499222, tzinfo=datetime.timezone.utc)),
        ),
    ]
