# Generated by Django 4.2.6 on 2023-10-30 06:16

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_expreiencmodel_image_alter_aboutmemodels_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentinfomodel',
            options={'verbose_name': 'contact info', 'verbose_name_plural': 'contacts info'},
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 16, 17, 557886, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='mobile_phone',
            field=models.CharField(blank=True, choices=[('ir', '+98')], default='ir', max_length=11, null=True, unique=True, verbose_name='mobile phone'),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 16, 17, 557886, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 16, 17, 557886, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreiencmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 16, 17, 557886, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetent',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 16, 17, 557886, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetentsciol',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 16, 17, 557886, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nvbarmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 16, 17, 557886, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 16, 17, 557886, tzinfo=datetime.timezone.utc)),
        ),
    ]
