# Generated by Django 4.2.6 on 2023-10-30 06:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_aboutmemodels_mobile_phone_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_code', models.CharField(max_length=5, verbose_name='mobile code')),
            ],
            options={
                'verbose_name': 'mobile code',
                'verbose_name_plural': 'mobile code',
                'db_tablespace': 'mobile_code',
            },
        ),
        migrations.RemoveField(
            model_name='aboutmemodels',
            name='mobile_phone_code',
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 22, 21, 41949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 22, 21, 41949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 22, 21, 41949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreiencmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 22, 21, 41949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetent',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 22, 21, 41949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetentsciol',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 22, 21, 41949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nvbarmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 22, 21, 41949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 6, 22, 21, 41949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='aboutmemodels',
            name='mobile_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='home.mobilecode', verbose_name='code'),
            preserve_default=False,
        ),
    ]
