# Generated by Django 4.2.6 on 2023-10-30 07:09

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_mobilecode_remove_aboutmemodels_mobile_phone_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExprienceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 7, 9, 28, 930100, tzinfo=datetime.timezone.utc))),
                ('title', models.CharField(max_length=50, verbose_name='title project')),
                ('project_url', models.URLField(verbose_name='project url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'projects',
            },
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 7, 9, 28, 930100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 7, 9, 28, 930100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 7, 9, 28, 930100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreiencmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 7, 9, 28, 930100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetent',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 7, 9, 28, 930100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetentsciol',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 7, 9, 28, 930100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nvbarmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 7, 9, 28, 930100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 7, 9, 28, 930100, tzinfo=datetime.timezone.utc)),
        ),
    ]
