# Generated by Django 4.2.6 on 2023-10-30 10:51

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_delete_contentinfomodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expreiencmodel',
            name='link_project',
        ),
        migrations.AddField(
            model_name='expreiencmodel',
            name='link_company',
            field=models.URLField(blank=True, null=True, verbose_name='link to company'),
        ),
        migrations.AlterField(
            model_name='aboutmemodels',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 10, 51, 12, 596327, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 10, 51, 12, 596327, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 10, 51, 12, 596327, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expreiencmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 10, 51, 12, 596327, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='exprienceproject',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 10, 51, 12, 596327, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetent',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 10, 51, 12, 596327, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='headerconetentsciol',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 10, 51, 12, 596327, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nvbarmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 10, 51, 12, 596327, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 10, 30, 10, 51, 12, 596327, tzinfo=datetime.timezone.utc)),
        ),
    ]
